version: '3'
services:
  db:
    image: mysql
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: .docker/Dockerfile-backend
    container_name: backend
    volumes:
      - .docker/supervisor.conf:/etc/supervisor/supervisord.conf
      - backend:/var/www/news-backend
    depends_on:
      - db

  react-app:
    build:
      context: .
      dockerfile: .docker/Dockerfile-frontend
    container_name: frontend
    volumes:
      - frontend:/var/www/news-frontend
    depends_on:
      - api

  webserver:
      image: httpd:2.4
      container_name: webserver
      ports:
          - "6070:6070"
          - "6071:6071"
      volumes:
          - .docker/httpd.conf:/usr/local/apache2/conf/httpd.conf
          - .docker/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
          - backend:/var/www/news-backend
          - frontend:/var/www/news-frontend
      depends_on:
          - api
          - react-app

volumes:
  backend:
  frontend:
  db:
