# Use an official Node.js runtime as base
FROM node:14

# Set the working directory in the container
WORKDIR /var/www/news-frontend

# Clone the React app from GitHub
RUN git clone https://github.com/mesoylu/news-frontend.git .

# Set permissions
RUN chown -R www-data:www-data .

# Install app dependencies
RUN npm install

# Build the React app
RUN npm run build
